### ISSUE TITLE
issue running JRuby (1.9)

### ISSUE THREAD

**Issue by anildigital** [kyledrake/sinatra-synchrony#14]
Get following errors, when tried to connect the 

....
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday.rb:15:in `method_missing'
 fetch_google.rb:9:in`**file**'
 org/jruby/RubyMethod.java:117:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:1152:in`compile!'
 org/jruby/RubyBasicObject.java:1717:in `instance_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in`route_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:708:in `route!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:758:in`process_route'
 org/jruby/RubyKernel.java:1205:in `catch'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in`process_route'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:707:in `route!'
 org/jruby/RubyArray.java:1603:in`each'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in `route!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:843:in`dispatch!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in `call!'
 org/jruby/RubyBasicObject.java:1717:in`instance_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `invoke'
 org/jruby/RubyKernel.java:1205:in`catch'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `invoke'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in`call!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:629:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:21:in`call'
 org/jruby/RubyProc.java:262:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in`initialize'
 org/jruby/RubyKernel.java:1419:in `loop'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in`initialize'
NoMethodError - undefined method `set_pending_connect_timeout' for EventMachine:Module:
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/em/connection.rb:496:in`set_pending_connect_timeout'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/em/connection.rb:490:in `pending_connect_timeout='
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:59:in`activate_connection'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/eventmachine.rb:671:in `bind_connect'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/eventmachine.rb:641:in`connect'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:52:in `activate_connection'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:83:in`setup_request'
 (eval):6:in `get'
 org/jruby/RubyBasicObject.java:1691:in`**send**'
 org/jruby/RubyKernel.java:2117:in `send'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/adapter/em_synchrony.rb:42:in`call'
 org/jruby/RubyProc.java:262:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/adapter/em_synchrony.rb:51:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/request/url_encoded.rb:14:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/connection.rb:203:in`run_request'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/connection.rb:85:in `get'
 org/jruby/RubyBasicObject.java:1691:in`**send**'
 org/jruby/RubyKernel.java:2117:in `send'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday.rb:15:in`method_missing'
 fetch_google.rb:9:in `__file__'
 org/jruby/RubyMethod.java:117:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:1152:in `compile!'
 org/jruby/RubyBasicObject.java:1717:in`instance_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in `route_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:708:in`route!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:758:in `process_route'
 org/jruby/RubyKernel.java:1205:in`catch'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in `process_route'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:707:in`route!'
 org/jruby/RubyArray.java:1603:in `each'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in`route!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:843:in `dispatch!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in`call!'
 org/jruby/RubyBasicObject.java:1717:in `instance_eval'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`invoke'
 org/jruby/RubyKernel.java:1205:in `catch'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`invoke'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in `call!'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/sinatra-1.2.6/lib/sinatra/base.rb:629:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:21:in `call'
 org/jruby/RubyProc.java:262:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `initialize'
 org/jruby/RubyKernel.java:1419:in`loop'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `initialize'
NoMethodError - undefined method`set_pending_connect_timeout' for EventMachine:Module:
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/em/connection.rb:496:in `set_pending_connect_timeout'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/em/connection.rb:490:in`pending_connect_timeout='
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:59:in `activate_connection'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/eventmachine.rb:671:in`bind_connect'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/eventmachine-1.0.0.beta.3-java/lib/eventmachine.rb:641:in `connect'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:52:in`activate_connection'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/em-http-request-1.0.0/lib/em-http/http_connection.rb:83:in `setup_request'
 (eval):6:in`get'
 org/jruby/RubyBasicObject.java:1691:in `__send__'
 org/jruby/RubyKernel.java:2117:in`send'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/adapter/em_synchrony.rb:42:in `call'
 org/jruby/RubyProc.java:262:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/adapter/em_synchrony.rb:51:in `call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/request/url_encoded.rb:14:in`call'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/connection.rb:203:in `run_request'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday/connection.rb:85:in`get'
 org/jruby/RubyBasicObject.java:1691:in `__send__'
 org/jruby/RubyKernel.java:2117:in`send'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/faraday-0.7.4/lib/faraday.rb:15:in `method_missing'
 fetch_google.rb:9:in`**file**'
 org/jruby/RubyMethod.java:117:in `call'
,,,

---

 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `initialize'
 org/jruby/RubyKernel.java:1419:in`loop'
 /Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `initialize'
java(82359,0x111fb5000) malloc: **\* error for object 0x102108630: pointer being freed was not allocated
**\* set a breakpoint in malloc_error_break to debug

**Comment by kyledrake** [comment]
Could you paste that error into pastie.org and send the link here? Github garbled your stack trace.

**Comment by kyledrake** [comment]
I'm closing this due to lack of activity.
