### ISSUE TITLE
Segmentation fault in fiber_pool

### ISSUE THREAD

**Issue by PetrKaleta** [kyledrake/sinatra-synchrony#16]
```
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75: [BUG] Segmentation fault
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]

-- control frame ----------
c:0031 p:---- s:0124 b:0124 l:000123 d:000123 CFUNC  :resume
c:0030 p:0067 s:0120 b:0120 l:000119 d:000119 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75
c:0029 p:0026 s:0115 b:0115 l:002648 d:002648 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:28
c:0028 p:0029 s:0110 b:0110 l:000109 d:000109 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.5/lib/rack/nulllogger.rb:9
c:0027 p:0015 s:0106 b:0106 l:000105 d:000105 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.5/lib/rack/head.rb:9
c:0026 p:0015 s:0099 b:0099 l:000098 d:000098 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/showexceptions.rb:21
c:0025 p:0018 s:0091 b:0091 l:001dd0 d:000090 BLOCK  /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334
c:0024 p:0032 s:0089 b:0089 l:000088 d:000088 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403
c:0023 p:0011 s:0085 b:0085 l:001dd0 d:001dd0 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334
c:0022 p:0216 s:0081 b:0081 l:000080 d:000080 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-parser-0.1.2/lib/rack/parser.rb:72
c:0021 p:0019 s:0072 b:0072 l:000071 d:000071 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-parser-0.1.2/lib/rack/parser.rb:61
c:0020 p:0020 s:0068 b:0068 l:000059 d:000067 BLOCK  /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:80
c:0019 p:---- s:0066 b:0066 l:000065 d:000065 FINISH
c:0018 p:---- s:0064 b:0064 l:000063 d:000063 CFUNC  :catch
c:0017 p:0135 s:0060 b:0060 l:000059 d:000059 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:78
c:0016 p:0088 s:0055 b:0054 l:000053 d:000053 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:53
c:0015 p:0036 s:0051 b:0051 l:000050 d:000050 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:38
c:0014 p:---- s:0046 b:0046 l:000045 d:000045 FINISH
c:0013 p:---- s:0044 b:0044 l:000043 d:000043 CFUNC  :run_machine
c:0012 p:0248 s:0041 b:0041 l:000040 d:000040 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:199
c:0011 p:0066 s:0034 b:0034 l:002530 d:002530 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/backends/base.rb:61
c:0010 p:0143 s:0030 b:0030 l:000029 d:000029 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/server.rb:159
c:0009 p:0545 s:0027 b:0027 l:0021c0 d:0021c0 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/controllers/controller.rb:86
c:0008 p:0283 s:0023 b:0023 l:000022 d:000022 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/runner.rb:185
c:0007 p:0037 s:0018 b:0018 l:000017 d:000017 METHOD /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/runner.rb:151
c:0006 p:0042 s:0015 b:0015 l:000014 d:000014 TOP    /Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/bin/thin:6
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :load
c:0003 p:0127 s:0007 b:0007 l:001098 d:000430 EVAL   /Users/Petr/.rvm/gems/ruby-1.9.2-p290/bin/thin:19
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:001098 d:001098 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/bin/thin:19:in `<main>'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/bin/thin:19:in `load'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/bin/thin:6:in `<top (required)>'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/runner.rb:151:in `run!'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/runner.rb:185:in `run_command'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/controllers/controller.rb:86:in `start'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/server.rb:159:in `start'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/backends/base.rb:61:in `start'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:199:in `run'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:199:in `run_machine'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:38:in `receive_data'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:53:in `process'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:78:in `pre_process'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:78:in `catch'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/thin-1.3.1/lib/thin/connection.rb:80:in `block in pre_process'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-parser-0.1.2/lib/rack/parser.rb:61:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-parser-0.1.2/lib/rack/parser.rb:72:in `_call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403:in `synchronize'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `block in call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.1/lib/sinatra/showexceptions.rb:21:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.5/lib/rack/head.rb:9:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.5/lib/rack/nulllogger.rb:9:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:28:in `call'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75:in `spawn'
/Users/Petr/.rvm/gems/ruby-1.9.2-p290/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75:in `resume'

-- C level backtrace information -------------------------------------------
```

**Comment by PetrKaleta** [comment]
Ha, its 1.9.2 problem on OSX Lion. Update to ruby 1.9.3-p0 solved this issue

https://github.com/mperham/rack-fiber_pool/issues/12

**Comment by inancgumus** [comment]
I'm having the same problem ... Will try to update now, thanks!!!

**Comment by inancgumus** [comment]
Yep, solved.
