### ISSUE TITLE
Redis PubSub: ruby-1.9.3-p0/gems/redis-3.0.1/lib/redis/connection/synchrony.rb:76:in `yield': can't yield from root fiber (FiberError)

### ISSUE THREAD

**Issue by pirj** [kyledrake/sinatra-synchrony#26]
Getting the error on first request:
`ruby-1.9.3-p0/gems/redis-3.0.1/lib/redis/connection/synchrony.rb:76:in `yield': can't yield from root fiber (FiberError)`

```
require 'sinatra'
require 'sinatra/base'
require 'redis'
require 'sinatra/synchrony'

class App < Sinatra::Base
  register Sinatra::Synchrony

  get '/' do
    redis = Redis.new(:host => "127.0.0.1", :port => 6379, :driver => :synchrony)
    stream do |out|
      redis.psubscribe('*') do |on|
        on.psubscribe do |channel, subscriptions|
          puts "Subscribed to ##{channel} (#{subscriptions} subscriptions)"
        end

        on.pmessage do |pattern, channel, message|
          puts "#{channel}: #{message}"
          out << "#{channel}: #{message}"
        end

        on.punsubscribe do |channel, subscriptions|
          puts "UNsubscribed to ##{channel} (#{subscriptions} subscriptions)"
        end
      end
    end
  end
end
```

**Comment by pirj** [comment]
Can reuse Redis.current here, but it uses plain Hiredis without EM. Will address this to redis-rb.
